version: '3.8'
services:
  client:
    container_name: client-area
    build: 
      context: ./client
      dockerfile: Dockerfile
      target: dev
    restart: always
    #image: cirrusci/flutter
    ports:
      - 3000:3000
    command: >
            sh -c "flutter pub get && flutter run -d web-server --web-port 3000 --web-hostname 0.0.0.0"
  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment:
      DEV_ENV: "TRUE"
    image: server-area
    ports:
      - 8080:8080